### ISSUE TITLE
govarnam module dependency version

### ISSUE THREAD

**Issue by Vonter** [varnamproject/govarnam-ibus#2]
Hi! I'm trying to build varnam-ibus-engine but it fails with this error:

`go: github.com/varnamproject/govarnam@v0.0.0-00010101000000-000000000000 (replaced by ../govarnam): reading ../govarnam/go.mod: open /home/user/govarnam/go.mod: no such
 file or directory`

I don't have experience with golang but to me it looks like it's because of the govarnam dependency version defined in these lines:

https://github.com/varnamproject/govarnam-ibus/blob/f6c20da27776d27b62fdd490c09fb0b05061bddd/go.mod#L9

https://github.com/varnamproject/govarnam-ibus/blob/f6c20da27776d27b62fdd490c09fb0b05061bddd/go.mod#L14-L15

Also nice work on this project :+1:

**Comment by subins2000** [comment]
Hi, thank you for reporting this. The project lacks some core documentation yeah. So to set it up, make a directory structure like this:

* govarnam : Clone https://github.com/varnamproject/govarnam
* govarnam-ibus : Clone https://github.com/varnamproject/govarnam-ibus

Then in `govarnam` folder:
```
make
sudo make install
sudo ldconfig
```
Or instead of `make install` you can make symlinks for the header files and `.so` to respective places in `/usr/local`.

Now we have the library and header files installed. So any app can now use govarnam.

Now let's build `govarnam-ibus`:
* Install dependencies of `gotk`: https://github.com/gotk3/gotk3
* Build:
```
make ubuntu-18
```
Building for Ubuntu 18 will work on 18, future versions and also on other Linux distros with GTK 3.22 and pango versions of Ubuntu 18.

After building you can install it:
```
sudo ./install.sh
```

Or instead of installing, you can symlink the files to necessary places:
```
sudo ln -s $(realpath varnam-ibus-engine) /usr/local/bin/varnam-ibus-engine
sudo ln -s $(realpath varnam-ml.png) /usr/local/share/varnam/ibus/icons/varnam-ml.png
sudo ln -s $(realpath component/varnam-ml.xml) /usr/share/ibus/component/varnam-ml.xml
```

Now open IBus Preferences -> Input Method and add the language input method.

Let me know if this worked out and then I can add the correct instructions to README.

**Comment by Vonter** [comment]
I am able to build it now following these steps. Thanks for the quick response!

**Comment by subins2000** [comment]
Great. For hacking on and then running the engine after changes, you can repeatedly do
```
go run -tags pango_1_42,gtk_3_22 . -s ml -lang ml -standalone
```
and then switching current ibus layout to Varnam. Make sure there's only one `varnam-ibus-engine` process running. A `pkill` before doing the above will be nice.
